server {
    listen 80;
    
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # This tells Nginx: "If you can't find a file, route the request back to index.html"
        # This allows React Router to handle the URL paths.
        try_files $uri $uri/ /index.html;
    }
}