apiVersion: apps/v1
kind: Deployment
metadata:
  name: koha-cms-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: koha-cms-backend
  template:
    metadata:
      labels:
        app: koha-cms-backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/rklsubha2017-cloud/admin-cms-docker/koha-cms-backend:4d5275e235cbdd96fa02525db17bf8a341e3b6a8
        ports:
        - containerPort: 8000
        # This injects all DB credentials and JWT/Vault keys automatically
        envFrom:
        - secretRef:
            name: koha-cms-secrets 

---
apiVersion: v1
kind: Service
metadata:
  name: koha-cms-backend-service
spec:
  selector:
    app: koha-cms-backend
  ports:
  - port: 8000
    targetPort: 8000